// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineTutorBookingSystem.Data;

#nullable disable

namespace OnlineTutorBookingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260507210540_FixTutorProfileNoSeed")]
    partial class FixTutorProfileNoSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TutorProfileId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorProfileId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            SubjectName = "English"
                        },
                        new
                        {
                            SubjectId = 2,
                            SubjectName = "Mathematics"
                        },
                        new
                        {
                            SubjectId = 3,
                            SubjectName = "Computer Science"
                        },
                        new
                        {
                            SubjectId = 4,
                            SubjectName = "Physics"
                        },
                        new
                        {
                            SubjectId = 5,
                            SubjectName = "Chemistry"
                        });
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.TutorProfile", b =>
                {
                    b.Property<int>("TutorProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorProfileId"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSuperTutor")
                        .HasColumnType("bit");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonsCount")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TutorProfileId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TutorProfiles");

                    b.HasData(
                        new
                        {
                            TutorProfileId = 1,
                            Availability = "Weekdays evenings",
                            Bio = "I help students build strong foundations in algebra and geometry.",
                            Country = "United States",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = "5 years of teaching",
                            Headline = "Experienced high school math tutor",
                            HourlyRate = 30m,
                            IsSuperTutor = true,
                            Languages = "English, Hindi",
                            LessonsCount = 520,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop",
                            Rating = 4.9m,
                            StudentsCount = 120,
                            SubjectId = 0,
                            UserId = 1
                        },
                        new
                        {
                            TutorProfileId = 2,
                            Availability = "Weekends",
                            Bio = "Focus on speaking skills and IELTS preparation.",
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Experience = "3 years",
                            Headline = "Conversational English and exam prep",
                            HourlyRate = 25m,
                            IsSuperTutor = false,
                            Languages = "English",
                            LessonsCount = 180,
                            ProfilePictureUrl = "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=200&h=200&fit=crop",
                            Rating = 4.7m,
                            StudentsCount = 45,
                            SubjectId = 0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("OnlineTutorBookingSystem.Models.User", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OnlineTutorBookingSystem.Models.TutorProfile", "TutorProfile")
                        .WithMany("Bookings")
                        .HasForeignKey("TutorProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TutorProfile");
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.TutorProfile", b =>
                {
                    b.HasOne("OnlineTutorBookingSystem.Models.Subject", "Subject")
                        .WithMany("TutorProfiles")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineTutorBookingSystem.Models.User", "User")
                        .WithOne("TutorProfile")
                        .HasForeignKey("OnlineTutorBookingSystem.Models.TutorProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.Subject", b =>
                {
                    b.Navigation("TutorProfiles");
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.TutorProfile", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("OnlineTutorBookingSystem.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("TutorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
